In [9]:
import numpy as np

In [10]:
a=np.array([1,2,3])

In [11]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [12]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [102]:
np.arange(10,25,5)

array([10, 15, 20])

In [16]:
e=np.linspace(0,2,9)

In [17]:
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [19]:
x=np.eye(2)
y=np.random.random((2,2))
x

array([[1., 0.],
       [0., 1.]])

In [20]:
y

array([[0.94625874, 0.19082911],
       [0.8482558 , 0.58603906]])

In [21]:
np.shape(a)

(3,)

In [22]:
np.shape(c)

(2, 2, 3)

In [23]:
np.shape(b)

(2, 3)

In [24]:
np.ndim(a)

1

In [25]:
np.ndim(b)

2

In [26]:
np.ndim(c)

3

In [27]:
np.size(a)

3

In [28]:
np.size(b)

6

In [29]:
np.size(c)

12

In [30]:
a.dtype

dtype('int32')

In [31]:
b.dtype

dtype('float64')

In [32]:
c.dtype

dtype('float64')

In [33]:
a.dtype.name

'int32'

In [34]:
b.dtype.name

'float64'

In [35]:
c.dtype.name

'float64'

In [36]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
x=np.multiply(b,b)

In [38]:
x

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [39]:
np.divide(a,a)

array([1., 1., 1.])

In [40]:
np.divide(b,a)

array([[1.5, 1. , 1. ],
       [4. , 2.5, 2. ]])

In [41]:
np.divide(b,b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.add(a,b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [104]:
np.subtract(b,a)

array([[0.5, 0. , 0. ],
       [3. , 3. , 3. ]])

In [44]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [45]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [46]:
np.sqrt(c)

array([[[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [47]:
np.add(b,b)

array([[ 3.,  4.,  6.],
       [ 8., 10., 12.]])

In [48]:
np.add(c,c)

array([[[ 3.,  4.,  6.],
        [ 8., 10., 12.]],

       [[ 6.,  4.,  2.],
        [ 8., 10., 12.]]])

In [122]:
np.max(b)

6.0

In [124]:
np.float64(6.0)

6.0

In [51]:
np.cumsum(b)

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [126]:
np.mean(a)

2.0

In [108]:
np.float64(2.0)

2.0

In [112]:
np.median(b)

3.5

In [114]:
np.float64(3.5)

3.5

In [116]:
np.std(a)

0.816496580927726

In [118]:
np.float64(0.816496580927726)

0.816496580927726